### ISSUE TITLE
Error:  Unexpected response: 404

### ISSUE THREAD

**Issue by spalaniappan-pg** [robinraju/release-downloader#280]
**Describe the bug**
I tried to use the actions for downloading the release assets based on the following options
1. latest field by setting it to true and removing other fields like Tag
2. setting latest field to false and assigning a Tag version 

In both the cases i get different error regarding the field:
I get Error: [getlatestRelease] Unexpected response: 404 when i use the latest field

If i use the tag instead of latest field then i get the same error for the tag
Error: [getReleaseByTag] Unexpected response: 404
Kindly let me know on how to solve this issue.

**Action Environment (please complete the following information):**
 - OS: [ubuntu-latest]

**Comment by robinraju** [comment]
@spalaniappan-pg Are you using this action to download assets from a private repo or a public one?
Would you mind sharing your action step/yaml here

**Comment by spalaniappan-pg** [comment]
Hi Yes its a Private repo. 
Below is the step i tried:

    - uses: robinraju/release-downloader@v1
      with:
        repository: "owner/repo"
        latest: true
        fileName: "Capture.PNG"
        zipBall: true

Below is the list of file i have for downloading from release asset:

![image](https://user-images.githubusercontent.com/61496082/128873231-fc02ca9c-808c-4b69-a0f1-efd0a43a2a03.png)


Fyi, at start i already checkout the project to get full access.

**Comment by robinraju** [comment]
Can you check if the secret `TOKEN_UPLOAD_RELEASE` contains a personal access token of the `user/organization` containing the repository from which you are downloading the release asset (with enough permissions)
cf: https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

I see this as the problem with your token

**Comment by spalaniappan-pg** [comment]
Hi Thanks for the suggestion. 
Just to update, i tried to create new access token and test the actions in a private repository to test the functionality to be sure that there is no issue with my organization tokens, it basically works when the zipBall or tarBall is set to false. When either one of these 2 fields are set to True, then an error occurs. Its a new error code.
Please find the image on the error. 
![image](https://user-images.githubusercontent.com/61496082/128920613-df7a19b8-67b5-47a0-8e93-ce27a12f960f.png)

**Comment by robinraju** [comment]
@spalaniappan-pg I found an issue within the download logic that prevented it from downloading `tarball/zipball`
A fix for it is now merged into `main`. You can use this action from its `main` branch as follows.

```yaml
   uses: robinraju/release-downloader@main
```
I can create a new release once you confirm it works for you.

**Comment by robinraju** [comment]
Closing this issue as the fix for it is now available in the [latest release](https://github.com/robinraju/release-downloader/releases/tag/v1.2)
Option for downloading all files is now changed to `fileName: "*"` I think that makes more sense than leaving it empty.
