### ISSUE TITLE
Print which release is latest

### ISSUE THREAD

**Issue by rfdonnelly** [robinraju/release-downloader#369]
**Is your feature request related to a problem? Please describe.**

Hi.  Thanks for sharing this Action.  It does exactly what I need.

I'm fetching the "latest" release for my project and it would be nice to know exactly which release was fetched.  When debugging a run, it is not always clear which release was the "latest" release at the time of the run.

**Describe the solution you'd like**

Something like:

```diff
 Run robinraju/release-downloader@v1.3
   with:
     repository: rfdonnelly/scma-gcal-sync
     latest: true
     fileName: scma-gcal-sync
     tarBall: false
     zipBall: false
     out-file-path: .
 Fetching latest release for repo rfdonnelly/scma-gcal-sync
 Downloading file: scma-gcal-sync to: /home/runner/work/scma-gcal-sync/scma-gcal-sync
+Downloaded release v1.2.0
 Done: /home/runner/work/scma-gcal-sync/scma-gcal-sync/scma-gcal-sync
```

**Describe alternatives you've considered**

I've considered manually printing the version information of the downloaded release (e.g. `program --version`) but details of how to implement this would be different for every project and it may not match the GitHub release.  The GitHub release information is more authoritative.

**Comment by robinraju** [comment]
To fetch the latest release, I'm using the GH API `repos/{repo-name}/releases/latest`
I tried with the repo you've specified `https://api.github.com/repos/rfdonnelly/scma-gcal-sync/releases/latest`
It returns `"tag_name": "v2.0.0-rc.3"`. 

In short: it's doable!

**Comment by robinraju** [comment]
@rfdonnelly I just merged a pr adding the requested change.

It now prints a log message as follows, if latest release is specified

```
Fetching latest release for repo robinraju/release-downloader-test
Found latest release version: v0.0.1
```
https://github.com/robinraju/release-downloader/runs/5057810179?check_suite_focus=true

You can test it on your repo using the action from main branch as follows.
```
- name: Download latest release
  uses: robinraju/release-downloader@main
```

This will be available in the next version of release-downloader.

**Comment by rfdonnelly** [comment]
Wow.  Brilliant.  Thank you!

Works great:

```diff
 Fetching latest release for repo rfdonnelly/scma-gcal-sync
+Found latest release version: v2.0.0-rc.3
 Downloading file: scma-gcal-sync to: /home/runner/work/scma-gcal-sync/scma-gcal-sync
 Done: /home/runner/work/scma-gcal-sync/scma-gcal-sync/scma-gcal-sync
```
