### ISSUE TITLE
Support wildcard for fileName

### ISSUE THREAD

**Issue by jsjoeio** [robinraju/release-downloader#422]
**Is your feature request related to a problem? Please describe.**
We want to be able to use a wildcard aka "*.deb" to download all assets with that file extension. 

**Describe the solution you'd like**
Support for `fileName: "*.deb"`

**Describe alternatives you've considered**
Download all files with `fileName: "*"`

**Additional context**
Seems like it would be implemented right here: https://github.com/robinraju/release-downloader/blob/2dd2f6632ea74de2327a706ea1037f5e090e6810/src/download.ts#L135

**Comment by robinraju** [comment]
@jsjoeio Glad, you find this `action` useful. 

I can add wildcard support for filenames. I am also thinking about adding support for multiple filenames by specifying them as an array if a user has requirements for specific files.

**Comment by jsjoeio** [comment]
Yes! We're using on code-server. Thanks for making it :)

Awesome! That would help us a ton.

**Comment by briantist** [comment]
Came to post this exact request, glad to see it's here and planned. Thanks for your work on this action!

**Comment by briantist** [comment]
Also want to add, it might be nice to default `fileName` to `'*'`, or at a minimum, enforce that it's "required".

Although it certainly was my own fault for not reading, I struggled for a while trying to figure out why it wasn't downloading anything before realizing that the default was _not_ `*`.

So, I think either it should have a default, or it should throw an error when nothing is supplied (at least, when nothing is combined with `tarBall: false` and `zipBall: false` as it was in my case). Or a warning maybe "no files will be downloaded" etc.

**Comment by robinraju** [comment]
WIldcard support for filenames is now available on the `main` branch. Thanks to @ricklambrechts 
I'll create a new release.
