### ISSUE TITLE
out-file-path and fileName seems to be mutually exclusive

### ISSUE THREAD

**Issue by tyteen4a03** [robinraju/release-downloader#550]
Using release-downloader@1.6; if I set both `out-file-path` and `fileName`, `fileName` gets ignored.

**Comment by robinraju** [comment]
@tyteen4a03 can you post the logs or be more specific on the action's behaviour? The expected behaviour is `fileName` gets downloaded into `out-file-path` and it is working fine for me.

**Comment by robinraju** [comment]
Closing this. Please reopen if you see this issue persists.
