### ISSUE TITLE
Can this action support for github app token?

### ISSUE THREAD

**Issue by Openedger** [robinraju/release-downloader#596]
For cross repositories release downloader, if I don't want to use PAT, can I use github app token instead?
like this: 
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Download release tar
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "XX/XX"
        latest: true
        fileName: "AAA"
        out-file-path: "xxx"
        token: ${{steps.generate_token.outputs.token}}

I tried, but failed.

**Comment by robinraju** [comment]
This action uses the [Releases](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases) API, and it supports GitHub apps. 
Can you check if your app has permission to access the target repo?

**Comment by Openedger** [comment]
Thanks for your feedback.
You are right. This action can work well now, after I checked/enabled all permission of github app's  repository permission.
Thanks a lot!!
