### ISSUE TITLE
Add support to extract release archives

### ISSUE THREAD

**Issue by hegerdes** [robinraju/release-downloader#612]
**Problem:**
Many GH Release publish multiple assets. Most of the time these assets are not directly usable because they are packages in an archive. A good example is the [prometheus](https://github.com/prometheus/prometheus/releases) repo where every asset is a `tar.gz` or `zip` archive.

To use the executables in the archive users must use or even install additional platform dependent tools to extract these. In GH Action this is a substantial overhad with at least one additional step in each workflow.

**Solution:**
I would like the option to automatically extract all archives while using this action. This action is based on NodeJS and has the power to extract files without handling platform specific requirements.

The alternative would be to use at least one or more additional steps to setup `tar`, `gzip` or a windows alternative for `zip` to extract files.

I will provide a reference implementation as soon as possible

**Comment by robinraju** [comment]
@pelkiegr just released a new version https://github.com/robinraju/release-downloader/releases/tag/v1.8
