### ISSUE TITLE
Error: [getReleaseByTag] Unexpected response: 401

### ISSUE THREAD

**Issue by tusarnayak108** [robinraju/release-downloader#624]
Dear @robinraju , i was trying to use this action, seeing 401 error always. Any clue?
![image](https://user-images.githubusercontent.com/47235632/234232229-5ef44375-2b99-40eb-9fa6-525eb366d580.png)

**Comment by robinraju** [comment]
I think you are missing the `token` part from the action's input.

**Comment by tusarnayak108** [comment]
yeh, token was wrong, now works. closing the ticket
