### ISSUE TITLE
Output version name

### ISSUE THREAD

**Issue by Madis0** [robinraju/release-downloader#647]
**Is your feature request related to a problem? Please describe.**
You currently have `tag_name` and `downloaded_files` as options, but there could be more.

**Describe the solution you'd like**
`version_name`

**Describe alternatives you've considered**
N/A

**Additional context**
For example, in your case it would output "Release Downloader v1.8" instead of "v1.8".

https://github.com/robinraju/release-downloader/releases/tag/v1.8

**Comment by robinraju** [comment]
As per Github api, this field is called as `name` inside the release object, 
I've added an output variable named `release_name` in #677
