### ISSUE TITLE
Downloaded file contents are incorrect starting with version 1.9

### ISSUE THREAD

**Issue by BelleNottelling** [robinraju/release-downloader#688]
**Describe the bug**

After upgrading from version 1.8 to 1.9, we ran into an issue where the translations were no longer working correctly inside of our application. (They are built on a separate repo and then downloaded when building the main app)

The hash of the file I am checking when downloaded (and extracted) through v1.8 is `03BFCE70E15EDC39B775E673B5E03FB2F71DAC16A216C4AB5A3803D8F36CE11E`.

When using the same config and using v 1.9, the resulting hash is `0BB2FCC4A185967658AE3D3172E80CC713212659BB59DD8884EF193E336F238C`.

**To Reproduce**
1. Download our latest [translation release](https://github.com/FOSSBilling/locale/releases/tag/latest) via version 1.8 and have it be extracted.
2. Then do the same with version 1.9.
3. Select the same file in both. You should specifically be comparing any of the `.mo` files as those are what we are having issues with.
4. Compare the hash of the selected files, they will be different. 

I really don't understand where this issue could be coming from, but it's certainly causing us issues

**Comment by me-axentia** [comment]
I have a similar experience. Our CI workflow fails when upgrading to version 1.9.
We download a .zip with just one file and extract it. But somehow it appears that the extracted file does not have the correct content.

**Comment by heinrich-ulbricht** [comment]
I did not double check but I also got trouble with downloaded and unzipped contents. Will check further and watch this issue.

**Comment by heinrich-ulbricht** [comment]
I can confirm that the new version 1.9 breaks files. Reverting to 1.8 solves this. That's a bit unnerving.

**Comment by BelleNottelling** [comment]
> That's a bit unnerving.

Indeed, we have now since replaced the action with shell commands so that we don't need to worry about extraction unexpectedly breaking

**Comment by robinraju** [comment]
Apologies for the late response. A new release with a fix for this issue is now available. Please test this and let me know if it fixes it. 

> The issue was caused after upgrading the node runtime to v20, and the library used to extract zip files broke the functionality. 

```
- uses: robinraju/release-downloader@v1.10
  with:
    fileName: "foo.zip"
    latest: true
    extract: true
```
