### ISSUE TITLE
Error: No assets found in release

### ISSUE THREAD

**Issue by TheVaan** [robinraju/release-downloader#700]
**Describe the bug**
When using release-downloader, the step fails because no asset could be found. The asset was created while creating a tag and also added to the release (see screenshot).
I have two jobs, the first one creates the release, the second one should download the asset to deploy to S3 bucket.
A debug log is attached below.
Am I doing something wrong?

**To Reproduce**
1. Create a tag and release via semantic-release in the first job.
2. Try to download the asset from the release in the second job.

**Expected behavior**
The attached asset should be downloaded and extracted.

**Screenshots**
<img width="935" alt="Bildschirmfoto 2024-03-02 um 22 58 19" src="https://github.com/robinraju/release-downloader/assets/1108485/5f67b038-ba25-4f61-931c-90cc9087146a">
<img width="549" alt="image" src="https://github.com/robinraju/release-downloader/assets/1108485/a0345872-12eb-4cc4-81fe-e496a6483bd9">

**Action Environment (please complete the following information):**
 - OS: ubuntu-latest

**Additional context**
Debug log:
```
##[debug]Evaluating condition for step: 'Getting asset 📦'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Getting asset 📦
##[debug]Loading inputs
##[debug]Evaluating: github.ref_name
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ref_name'
##[debug]=> 'v3.1.9'
##[debug]Result: 'v3.1.9'
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.repository
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'repository'
##[debug]=> 'milhouse-solutions/apothekia-frontend'
##[debug]Result: 'milhouse-solutions/apothekia-frontend'
##[debug]Loading env
Run robinraju/release-downloader@v1.9
  with:
    tag: v3.1.9
    tarBall: true
    extract: true
    token: ***
    repository: milhouse-solutions/apothekia-frontend
    latest: false
    preRelease: false
    fileName: *
    zipBall: false
    out-file-path: .
    github-api-url: https://api.github.com/
Fetching release v3.1.9 from repo milhouse-solutions/apothekia-frontend
Found release tag: v3.1.9
Error: No assets found in release v3.1.9
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Getting asset 📦
```

My jobs config:
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment || 'staging' }}
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Getting asset 📦
        uses: robinraju/release-downloader@v1.9
        with:
          tag: ${{ github.ref_name }}
          tarBall: true
          extract: true
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by TheVaan** [comment]
Found out I failed on creating the asset.

**Comment by Vaishno23** [comment]
may i know how did you fixed it?

**Comment by TheVaan** [comment]
@Vaishno23 I forgot to bundle the dist folder and attach it to the tag/release. The zip/tar of the source code that are listed as assets but are not the type of asset this action is looking for.
