### ISSUE TITLE
v1 is not conforming to GitHub's release management policy and points at outdated v1.0 version

### ISSUE THREAD

**Issue by inkarkat** [robinraju/release-downloader#749]
**Describe the bug**

The `v1` tag is supposed to point at the latest (`v1.11` at the moment), but instead here it's actually a very first `v1.0` release from four years ago.
Consumers that want to automatically obtain minor and patch releases and therefore use `robinraju/release-downloader@v1` are inadvertently stuck with a very outdated release!

Cp. the [GitHub actions release recommendations](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management):

> Move the major version tag (such as v1, v2) to point to the Git ref of the current release.

**To Reproduce**

```
- uses: robinraju/release-downloader@v1
```

Build has warnings:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: robinraju/release-downloader@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> The following actions uses node12 which is deprecated and will be forced to run on node16: robinraju/release-downloader@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by robinraju** [comment]
@inkarkat Thanks for spotting this issue. I've linked the latest version `v1.11` to the `v1` tag.
You can now use 
```
- uses: robinraju/release-downloader@v1
```

I am working on automating the process.

**Comment by inkarkat** [comment]
Great, thank you! I think it makes a lot of sense to automate that via a GitHub action, too.

I'm not a huge fan of GitHub's versioning approach (others have commented already that it would be nice to allow some sort of version ranges in consuming actions instead, or at least they should recommend to use branches instead of moving tags), but given that most actions stick to this scheme, actions should adhere to it for now.

I think issue can be closed.
